name: Build and Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

- name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ../../environment.yml  
          auto-activate-base: false
          activate-environment: ibtd 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst-parser numpydoc 
          # Add any other Sphinx extensions you use

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
